
name: "new-research-dev"
services:
  backend:
    build: ./backend
    container_name: new_research_backend_dev
    ports:
      - "56733:8080"
    volumes:
      - ./backend:/app
    env_file:
      - .env.dev
    environment:
      - FLASK_RUN_PORT=8080
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: new_research_frontend_dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
  db:
    image: postgres:13-alpine
    container_name: new_research_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    restart: unless-stopped
volumes:
  # persistent volume on host at
  # /var/lib/docker/postgres_data
  postgres_data: